#ValueError
from datetime import time
mytime = time(hour = 25)
